swagger: "2.0"
info:
  title: Enduro API
  version: ""
host: localhost:9000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /collection:
    get:
      tags:
      - collection
      summary: list collection
      description: List all stored collections
      operationId: collection#list
      parameters:
      - name: original_id
        in: query
        description: ID of the original dataset
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionEnduroStoredCollectionResponseCollection'
      schemes:
      - http
  /collection/{id}:
    get:
      tags:
      - collection
      summary: show collection
      description: Show collection by ID
      operationId: collection#show
      parameters:
      - name: id
        in: path
        description: Identifier of collection to show
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionShowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
    delete:
      tags:
      - collection
      summary: delete collection
      description: Delete collection by ID
      operationId: collection#delete
      parameters:
      - name: id
        in: path
        description: Identifier of collection to delete
        required: true
        type: integer
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionDeleteNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/cancel:
    post:
      tags:
      - collection
      summary: cancel collection
      description: Cancel collection processing by ID
      operationId: collection#cancel
      parameters:
      - name: id
        in: path
        description: Identifier of collection to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionCancelNotRunningResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionCancelNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/retry:
    post:
      tags:
      - collection
      summary: retry collection
      description: Retry collection processing by ID
      operationId: collection#retry
      parameters:
      - name: id
        in: path
        description: Identifier of collection to retry
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionRetryNotRunningResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionRetryNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/workflow:
    get:
      tags:
      - collection
      summary: workflow collection
      description: Retrieve workflow status by ID
      operationId: collection#workflow
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionWorkflowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionWorkflowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /swagger/swagger.json:
    get:
      summary: Download internal/api/gen/http/openapi.json
      description: JSON document containing the API swagger definition.
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CollectionCancelNotFoundResponseBody:
    title: CollectionCancelNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 15222102461692857061
        format: int64
      message:
        type: string
        description: Message of error
        example: Dignissimos iusto harum sunt omnis.
    description: Collection not found
    example:
      id: 10537761642927230266
      message: Quaerat sunt nihil ipsam harum quaerat molestiae.
    required:
    - message
    - id
  CollectionCancelNotRunningResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: cancel_not_running_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionDeleteNotFoundResponseBody:
    title: CollectionDeleteNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 14226663540695118796
        format: int64
      message:
        type: string
        description: Message of error
        example: Reiciendis laborum deserunt quasi ea quisquam et.
    description: Collection not found
    example:
      id: 10218096377579778616
      message: Accusantium fugiat asperiores id eos molestiae deserunt.
    required:
    - message
    - id
  CollectionEnduroStoredCollectionResponseCollection:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/EnduroStoredCollectionResponse'
    description: ListResponseBody is the result type for an array of EnduroStored-CollectionResponse
      (default view)
    example:
    - aip_id: 35814117-F834-9FAB-0A03-DB6E91CE1F7F
      completed_at: "2009-12-09T03:01:06Z"
      created_at: "1995-10-13T20:15:10Z"
      id: 3259554584549474690
      name: Velit suscipit.
      original_id: Corporis sint aut consequatur itaque similique rerum.
      run_id: 76150F6F-C16D-33A6-B049-F5AE2D7C6385
      status: new
      transfer_id: AC2E8D12-84E7-ADAA-5045-93C4FF40145F
      workflow_id: 43632E4F-A034-6412-7CEA-7CD0E1AED81D
    - aip_id: 35814117-F834-9FAB-0A03-DB6E91CE1F7F
      completed_at: "2009-12-09T03:01:06Z"
      created_at: "1995-10-13T20:15:10Z"
      id: 3259554584549474690
      name: Velit suscipit.
      original_id: Corporis sint aut consequatur itaque similique rerum.
      run_id: 76150F6F-C16D-33A6-B049-F5AE2D7C6385
      status: new
      transfer_id: AC2E8D12-84E7-ADAA-5045-93C4FF40145F
      workflow_id: 43632E4F-A034-6412-7CEA-7CD0E1AED81D
  CollectionRetryNotFoundResponseBody:
    title: CollectionRetryNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 2184433264373895287
        format: int64
      message:
        type: string
        description: Message of error
        example: Quis voluptatem aut aliquid enim ex sint.
    description: Collection not found
    example:
      id: 6018078740366151090
      message: Fugit ipsam.
    required:
    - message
    - id
  CollectionRetryNotRunningResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: retry_not_running_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionShowNotFoundResponseBody:
    title: CollectionShowNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 16315716654770573020
        format: int64
      message:
        type: string
        description: Message of error
        example: Optio minus aut et.
    description: Collection not found
    example:
      id: 16480092006965201264
      message: Eligendi quos dolores corporis quidem rerum.
    required:
    - message
    - id
  CollectionShowResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; view=default'
    type: object
    properties:
      aip_id:
        type: string
        description: Identifier of Archivematica AIP
        example: A1E767AB-DA97-F23F-D106-18BF8653EB6C
        format: uuid
      completed_at:
        type: string
        description: Completion datetime
        example: "1976-08-19T14:34:42Z"
        format: date-time
      created_at:
        type: string
        description: Creation datetime
        example: "2011-02-08T18:37:32Z"
        format: date-time
      id:
        type: integer
        description: Identifier of collection
        example: 2453144221760337626
        format: int64
      name:
        type: string
        description: Name of the collection
        example: Odio maxime quam rem dignissimos quia.
      original_id:
        type: string
        description: Identifier provided by the client
        example: Quibusdam eaque perferendis ut similique facere.
      run_id:
        type: string
        description: Identifier of latest processing workflow run
        example: 6E989AEF-9C11-4862-D8B1-5CFC4F6414E0
        format: uuid
      status:
        type: string
        description: Status of the collection
        default: new
        example: new
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
      transfer_id:
        type: string
        description: Identifier of Archivematica transfer
        example: 8B791A71-1C43-AB9B-4366-12192353E1A2
        format: uuid
      workflow_id:
        type: string
        description: Identifier of processing workflow
        example: 6BD40BD6-7AF6-FB4E-C1C1-23700A0E68DE
        format: uuid
    description: ShowResponseBody result type (default view)
    example:
      aip_id: 0866BAED-0A78-C310-5523-F8F1C3A1D14C
      completed_at: "1989-07-11T06:40:24Z"
      created_at: "2006-05-24T14:00:24Z"
      id: 4819873748900045547
      name: Similique voluptatibus consequatur in quaerat dolorum quis.
      original_id: Aut vel quisquam aut.
      run_id: 36111869-D7E7-159A-3E5F-AC3C2E0C42DD
      status: error
      transfer_id: C14F18CD-9DAC-4197-F250-EC3FBAFE81DD
      workflow_id: EBC096AD-D9EC-2F9C-CCD5-2819684939D3
    required:
    - id
    - status
    - created_at
  CollectionWorkflowNotFoundResponseBody:
    title: CollectionWorkflowNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 6193006552320250870
        format: int64
      message:
        type: string
        description: Message of error
        example: Velit consequatur nobis delectus.
    description: Collection not found
    example:
      id: 5410736015454181723
      message: Omnis corporis et sunt ut esse consectetur.
    required:
    - message
    - id
  CollectionWorkflowResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-status;
      view=default'
    type: object
    properties:
      history:
        $ref: '#/definitions/EnduroCollectionWorkflowHistoryResponseBodyCollection'
      status:
        type: string
        example: Ratione iste dolorem rerum maxime dicta a.
    description: WorkflowResponseBody result type (default view)
    example:
      history:
      - details: Cum nihil quis.
        id: 5423793215779300
        type: Numquam sit sint est.
      - details: Cum nihil quis.
        id: 5423793215779300
        type: Numquam sit sint est.
      - details: Cum nihil quis.
        id: 5423793215779300
        type: Numquam sit sint est.
      - details: Cum nihil quis.
        id: 5423793215779300
        type: Numquam sit sint est.
      status: Sit quibusdam quidem consectetur praesentium.
  EnduroCollectionWorkflowHistoryResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-history;
      view=default'
    type: object
    properties:
      details:
        description: Contents of the event
        example: Est deserunt.
      id:
        type: integer
        description: Identifier of collection
        example: 16792889764074458392
        format: int64
      type:
        type: string
        description: Type of the event
        example: Fuga laborum maiores et esse.
    description: WorkflowHistoryEvent describes a history event in Cadence. (default
      view)
    example:
      details: Quas corrupti illum cumque qui facilis omnis.
      id: 836257256755188405
      type: Ex labore iste eveniet nihil sint omnis.
  EnduroCollectionWorkflowHistoryResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-history;
      type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/EnduroCollectionWorkflowHistoryResponseBody'
    description: EnduroCollection-Workflow-HistoryCollectionResponseBody is the result
      type for an array of EnduroCollection-Workflow-HistoryResponseBody (default
      view)
    example:
    - details: Cum nihil quis.
      id: 5423793215779300
      type: Numquam sit sint est.
    - details: Cum nihil quis.
      id: 5423793215779300
      type: Numquam sit sint est.
    - details: Cum nihil quis.
      id: 5423793215779300
      type: Numquam sit sint est.
  EnduroStoredCollectionResponse:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; view=default'
    type: object
    properties:
      aip_id:
        type: string
        description: Identifier of Archivematica AIP
        example: 7F641448-35F7-7B05-AFB4-8DFCC48CED66
        format: uuid
      completed_at:
        type: string
        description: Completion datetime
        example: "1984-11-21T05:39:13Z"
        format: date-time
      created_at:
        type: string
        description: Creation datetime
        example: "1985-02-16T09:10:38Z"
        format: date-time
      id:
        type: integer
        description: Identifier of collection
        example: 4074833407011102259
        format: int64
      name:
        type: string
        description: Name of the collection
        example: Vel maiores aliquam dolorum odio.
      original_id:
        type: string
        description: Identifier provided by the client
        example: Quam ut veniam.
      run_id:
        type: string
        description: Identifier of latest processing workflow run
        example: A8E7C55C-B3EA-B228-EF84-9DB3D55D57A4
        format: uuid
      status:
        type: string
        description: Status of the collection
        default: new
        example: in progress
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
      transfer_id:
        type: string
        description: Identifier of Archivematica transfer
        example: 1576BB1F-D21C-05AD-6677-73725A387FA6
        format: uuid
      workflow_id:
        type: string
        description: Identifier of processing workflow
        example: 233374F1-297F-8711-5FC3-4F6B3731AD63
        format: uuid
    description: StoredPackage describes a collection retrieved by the service. (default
      view)
    example:
      aip_id: E31B6C92-4A10-2D9D-2B43-B3362900308F
      completed_at: "2002-04-11T04:56:10Z"
      created_at: "2015-12-13T05:57:03Z"
      id: 13590445315752194118
      name: Magni et molestiae.
      original_id: Sapiente sit.
      run_id: F25C441B-B3AA-5871-1077-53EACA084D5A
      status: unknown
      transfer_id: E058AD50-5D7F-E9A8-E010-D33044724992
      workflow_id: CEF3CAF7-AB82-083A-2F08-9497BE6B7488
    required:
    - id
    - status
    - created_at
